### ISSUE TITLE
有类似CLIP这样文字-图片的中文模型吗

### ISSUE THREAD

**Issue by troilus-canva** [lonePatient/awesome-pretrained-chinese-nlp-models#2]

**Comment by lonePatient** [comment]
@troilus-canva 目前好像还没中文多模态的预训练模型公开的。后续我关注下

**Comment by troilus-canva** [comment]
我找到一篇最近的新论文，但是他的代码和预训练模型也都没有公开
https://arxiv.org/abs/2103.06561

**Comment by troilus-canva** [comment]
代码刚刚公开了
https://github.com/BAAI-WuDao/BriVlL

**Comment by lonePatient** [comment]
@troilus-canva  WWenLan模型权重公开了，README.md增加了对应的下载链接

**Comment by vincentLk** [comment]
> 

好像不能随意下载，只能提申请

**Comment by yangapku** [comment]
大家好，我们是阿里达摩院OFA-Sys团队，我们近期重新开源了Chinese-CLIP repo（https://github.com/OFA-Sys/Chinese-CLIP ）除了之前的开放内容，这次我们带着更多模型规模、检索demo以及详尽的技术报告诚意归来，同时在达摩院重磅平台ModelScope同步集成上线。希望大家多多试用 & star，多提宝贵意见～
