### ISSUE TITLE
DeepSeek-V2-Base参数写错, 其为"A21B/236B"

### ISSUE THREAD

**Issue by Night-Quiet** [lonePatient/awesome-pretrained-chinese-nlp-models#27]

**Comment by lonePatient** [comment]
@Night-Quiet 已更新，非常感谢！

**Comment by Night-Quiet** [comment]
@kafakigang 不理解, 从star history来看, 增长挺平稳的. 从哪里看出"一周暴涨 4535 Star"?

<img width="1004" height="668" alt="Image" src="https://github.com/user-attachments/assets/92ca2af8-ea90-4102-947f-be8e27c2d9d3" />
